
	
		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
						<li class="list-group-item active"><a href="/">Tarefas pendentes</a></li>
						<li class="list-group-item"><a href="/nova_tarefa">Nova tarefa</a></li>
						<li class="list-group-item"><a href="/todas_tarefas">Todas tarefas</a></li>
					</ul>
				</div>

				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Tarefas pendentes</h4>
								<hr />
								<?php foreach ($this->view->tarefas  as $id => $tarefas) { ?>
								<div class="row mb-3 d-flex align-items-center tarefa">
									<div class="col-sm-9"><p><strong><?=$tarefas['tarefa'] ?></strong> <span class="text text-muted"><?=$tarefas['data'] ?></span></p></div>
									<div class="col-sm-3 mt-2 d-flex justify-content-between">
										<i class="fas fa-trash-alt fa-lg text-danger"></i>
										<i class="fas fa-edit fa-lg text-info"></i>
										<i class="fas fa-check-square fa-lg text-success"></i>
									</div>
								</div>
							 	<?php } ?>	
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>